const ICONS = {
  globe: '🌍',
  tree: '🌳',
  altar: '🪨',
  ship: '⛵',
  tower: '🧱',
  tent: '⛺',
  stars: '✨',
  baby: '👶',
  ram: '🐏',
  ladder: '🪜',
  staff: '🪄',
  coat: '🧥',
  grain: '🌾',
  chains: '⛓️',
  flame: '🔥',
  lamb: '🐑',
  waves: '🌊',
  tablets: '📜',
  tabernacle: '⛪',
  grapes: '🍇',
  river: '🏞️',
  trumpet: '🎺',
  map: '🗺️',
  cycle: '🔁',
  palm: '🌴',
  torch: '🏺',
  pillar: '🏛️',
  wheat: '🌾',
  lamp: '🪔',
  crown: '👑',
  sling: '🎯',
  city: '🏙️',
  throne: '🪑',
  temple: '🏛️',
  'split-crown': '⚔️',
  'fire-altar': '🔥',
  mantle: '🧣',
  'broken-city': '🏚️',
  shield: '🛡️',
  scroll: '📜',
  'burning-temple': '🔥',
  lion: '🦁',
  'crown-scroll': '👑',
  'rebuilt-temple': '🏛️',
  wall: '🧱',
  'river-dove': '🕊️',
  star: '⭐',
  dove: '🕊️',
  'mountain-scroll': '⛰️',
  'cross-tomb': '✝️'
};

export function getIcon(icon) {
  return ICONS[icon] || '📍';
}
